version: "3.8"

services:
  dash-spa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-spa
    networks:
      - dev-ecommpay-pp-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.dash_spa_https.rule=Host(`welcome.o10r.io`)
      - traefik.http.routers.dash_spa_https.tls=true
      - traefik.http.routers.dash_spa_https.entrypoints=https
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development

networks:
  dev-ecommpay-pp-network:
    name: dev-ecommpay-pp-network
    external: true
